// <auto-generated />
namespace PvPGamingWebsite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ImageInNewsPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageInNewsPost));
        
        string IMigrationMetadata.Id
        {
            get { return "201504271853089_ImageInNewsPost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
