// <auto-generated />
namespace PvPGamingWebsite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TeamMembersTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TeamMembersTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201504142018361_TeamMembersTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
